// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using waqeel.Models;

#nullable disable

namespace waqeel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("waqeel.Models.Account", b =>
                {
                    b.Property<long>("AccountCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AccountCode"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<long?>("ParentCode")
                        .HasColumnType("bigint");

                    b.HasKey("AccountCode");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("waqeel.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DriverId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("waqeel.Models.Item", b =>
                {
                    b.Property<int>("ItemCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemCode"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemCode");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("waqeel.Models.JournalDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AccountCode")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Credit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Debit")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("JournalHeaderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JournalHeaderId");

                    b.ToTable("JournalDetails");
                });

            modelBuilder.Entity("waqeel.Models.JournalHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JournalNo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("JournalHeaders");
                });

            modelBuilder.Entity("waqeel.Models.PackingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("FarmerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PackingRecords");
                });

            modelBuilder.Entity("waqeel.Models.PurchaseInvoice", b =>
                {
                    b.Property<int>("InvoiceNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvoiceNo"));

                    b.Property<decimal>("AgencyCommissionAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AgencyCommissionPercent")
                        .HasColumnType("numeric");

                    b.Property<bool>("ApplyAgencyCommission")
                        .HasColumnType("boolean");

                    b.Property<bool>("ApplyZakat")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FarmerAccountCode")
                        .HasColumnType("bigint");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OtherDiscountAccountId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OtherDiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("PackingRecordId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalGrossAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ZakatAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ZakatPercent")
                        .HasColumnType("numeric");

                    b.HasKey("InvoiceNo");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("waqeel.Models.Voucher", b =>
                {
                    b.Property<int>("VoucherNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VoucherNo"));

                    b.Property<long>("AccountCode")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VoucherNo");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("waqeel.Models.JournalDetail", b =>
                {
                    b.HasOne("waqeel.Models.JournalHeader", null)
                        .WithMany("Details")
                        .HasForeignKey("JournalHeaderId");
                });

            modelBuilder.Entity("waqeel.Models.JournalHeader", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
